var namespaces_dup =
[
    [ "ANSI", "namespace_a_n_s_i.html", null ],
    [ "color", "namespacecolor.html", null ],
    [ "env", "namespaceenv.html", null ],
    [ "ex", "namespaceex.html", null ],
    [ "facet", "namespacefacet.html", null ],
    [ "file", "namespacefile.html", "namespacefile" ],
    [ "gen1", "namespacegen1.html", null ],
    [ "gen2", "namespacegen2.html", null ],
    [ "ini", "namespaceini.html", null ],
    [ "iter", "namespaceiter.html", null ],
    [ "math", "namespacemath.html", null ],
    [ "matrix", "namespacematrix.html", null ],
    [ "op", "namespaceop.html", null ],
    [ "opt", "namespaceopt.html", "namespaceopt" ],
    [ "optional", "namespaceoptional.html", null ],
    [ "process", "namespaceprocess.html", null ],
    [ "Query", "namespace_query.html", null ],
    [ "rng", "namespacerng.html", "namespacerng" ],
    [ "seed", "namespaceseed.html", null ],
    [ "seq", "namespaceseq.html", null ],
    [ "str", "namespacestr.html", "namespacestr" ],
    [ "term", "namespaceterm.html", "namespaceterm" ],
    [ "token", "namespacetoken.html", "namespacetoken" ],
    [ "var", "namespacevar.html", null ],
    [ "xlog", "namespacexlog.html", null ]
];