name: Update Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  update-documentation:
    runs-on: ubuntu-latest

    steps:
      # Clone the repository
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
      
      # Clone the gh-pages branch into ./307lib/gh-pages
      - name: 'Clone the Documentation'
        run:  git clone --single-branch --branch gh-pages https://github.com/radj307/307lib gh-pages
      
      - name: Install Doxygen
        run:  apt-get update && apt-get install -y doxygen graphviz
        
      - name: Run Doxygen
        run:  |
              cd "${{github.workspace}}/gh-pages"
              doxygen ./Doxyfile

      - name: Commit Changes
        run:  |
              cd ${{github.workspace}}/gh-pages
              git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
              git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
              git add -A && git commit -m "Update Documentation"
              git push
