name: Update Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      is-dry-run:
        type: boolean
        required: false
        default:  'false'

jobs:
  update-documentation:
    runs-on: ubuntu-latest

    steps:
      # Clone the repository
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          persist-credentials: false
      
      # Clone the gh-pages branch into ./307lib/gh-pages
      - name: 'Clone the Documentation'
        run:  git clone --single-branch --branch gh-pages https://github.com/radj307/307lib gh-pages

      - name: 'Print Debugging Information'
        run:  |
              echo ${{github.workspace}}
              echo "########## github.workspace:"
              ls -lAgh ${{github.workspace}}
              echo "########## WORKING DIRECTORY:"
              ls -lAgh ./

      - name: Install Doxygen
        run:  sudo apt-get update && sudo apt-get install doxygen graphviz -y
        
      - name: Run Doxygen
        run:  |
              cd gh-pages
              doxygen ./Doxyfile
       
#      - name: Run doxygen
#        uses: radj307/action-doxygen@v0.2
#        with:
#          working-dir: ${{github.workspace}}/gh-pages

      - name: 'Configure actions git user'
        uses: fregante/setup-git-user@v1.0.1
      
      - name: Commit Changes
        if:   github.event.inputs.is-dry-run == false
        run:  |
              cd ${{github.workspace}}/gh-pages
              git add -A
              git commit -m "Update Documentation"
              git push -u origin gh-pages
