name: Update Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  update-documentation:
    runs-on: ubuntu-latest

    steps:
      # Clone the repository
      - name: Clone the Main Branch
        uses: actions/checkout@v2
        with:
          submodules:   recursive
          ref:          main
          
      - name: Clone the Documentatioon Branch
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref:        gh-pages
          path:       gh-pages
      
      # Clone the gh-pages branch into ./307lib/gh-pages
      #- name: Clone the Documentation
      #  run:  |
      #        git clone --single-branch --branch gh-pages https://github.com/radj307/307lib gh-pages && cd gh-pages
      #        git submodule update --init --recursive
      
      - name: Install Doxygen & Graphviz
        run:  sudo apt-get update && sudo apt-get install -y doxygen graphviz
        
      - name: Run Doxygen
        run:  |
              cd "${{github.workspace}}/gh-pages"
              doxygen ./Doxyfile
              
      - name: Commit Changes
        run:  |
              git config user.name github-actions
              git config user.email github-actions@github.com
              git add -A && git commit -m "Generated Documentation"
              git push
